version: 2.1
orbs:
  codecov: codecov/codecov@5
jobs:
  test:
    environment:
      CODECOV_TOKEN: $CODECOV_TOKEN
    docker:
      - image: cimg/node:22.19.0
    working_directory: ~/repo
    resource_class: large
    steps:
      - checkout
      - run:
          name: set GIT name and email
          command: |
            git config --global -l
            git config --global user.email "$GIT_COMMITTER_EMAIL"
            git config --global user.name "$GIT_COMMITTER_NAME"
            git config --global -l
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - strapi-plugin-open-mercato-1726588800-{{ checksum "yarn.lock" }}
            - strapi-plugin-open-mercato-1726588800
      - run:
          name: Echo versions
          command: |
            node --version
            yarn --version
      - run:
          name: Configure NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Install
          command: |
            yarn install
      - run:
          name: Test
          command: |
            yarn test:server:ci
      - codecov/upload:
          flags: unittest
      - save_cache:
          paths:
            - ./node_modules
          key: strapi-plugin-open-mercato-1726588800-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    docker:
      - image: cimg/node:22.19.0
    working_directory: ~/repo
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Configure NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Build
          command: |
            yarn build
      - run:
          name: Publish package
          command: npm publish --tag latest
  deployBeta:
    docker:
      - image: cimg/node:22.19.0
    working_directory: ~/repo
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Configure NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Build
          command: |
            yarn build
      - run:
          name: Publish package
          command: npm publish --tag beta
workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - deployBeta:
          requires:
            - test
          filters:
            tags:
              only: /^v.*-beta\.\d+$/
            branches:
              ignore: /.*/
